Modified cross-server error message

diff --git a/qstat b/qstat
--- a/qstat
+++ b/qstat
@@ -187,7 +187,7 @@ while [[ $# -gt 0 ]]; do
             ;;
         *)
             if [[ -n $CUSTOM_SERVER ]] || [[ "$@" == *@* ]]; then
-                >&2 echo "Error: option $1 only available on current server ($QSCACHE_SERVER)"
+                >&2 echo "Error: option $1 is not available across servers"
                 exit 1
             fi
 
