Added notice for unsupported options across servers

diff --git a/qstat b/qstat
--- a/qstat
+++ b/qstat
@@ -186,6 +186,11 @@ while [[ $# -gt 0 ]]; do
             fi
             ;;
         *)
+            if [[ -n $CUSTOM_SERVER ]] || [[ "$@" == *@* ]]; then
+                >&2 echo "Error: option $1 only available on current server ($QSCACHE_SERVER)"
+                exit 1
+            fi
+
             load_config
 
             if [[ ! -f $QSTATBIN ]]; then
