Better multi-server support

diff --git a/qstat b/qstat
--- a/qstat
+++ b/qstat
@@ -106,6 +106,26 @@ function log_usage {
     fi
 }
 
+# Function to decode and load settings for other supported servers
+function find_server {
+    if [[ ! -f $MYPATH/${CUSTOMSERVER}.cfg ]]; then
+        load_config
+
+        for PBSSERVER in $SERVERMAP; do
+            if [[ $PBSSERVER == $CUSTOMSERVER=* ]]; then
+                CUSTOMSERVER=${PBSSERVER#*=}
+            fi
+        done
+    fi
+
+    if [[ ! -f $MYPATH/${CUSTOMSERVER}.cfg ]]; then
+        >&2 echo "Error: server $CUSTOMSERVER not recognized"
+        exit 1
+    fi
+    
+    QSCACHE_SERVER=$CUSTOMSERVER
+}
+
 # Avoid infinite recursion
 if [[ $QSCACHE_RECURSION == true ]]; then
     echo "Fatal: PBS qstat location could not be determined" >&2
@@ -120,9 +140,9 @@ MYPATH=$(dirname $(readlink -f $0))
 JOBLIST= USERSTR= NOLABELS= CUSTOMSERVER=
 ARGLIST="$*"
 DATAFILE=joblist-default.dat
-COPER="!="
+COPER="!~"
 AWKOPT=print
-STATCODE=F
+STATCODE="[FM]"
 HN=$(hostname)
 
 # Check for bypass setting
@@ -156,7 +176,7 @@ while [[ $# -gt 0 ]]; do
 			;;
         --status)
             STATCODE="$2"
-            COPER="=="
+            COPER="~"
             shift; ;;
         -u)
             DATAFILE=${DATAFILE/default/info}
@@ -169,7 +189,14 @@ while [[ $# -gt 0 ]]; do
         -x)
             STATCODE=
             ;;
+        @*)
+            CUSTOMSERVER=${1:1} find_server
+            ;;
 		[0-9]*)
+            if [[ $1 == *.* ]]; then
+                CUSTOMSERVER=${1#*.} find_server
+            fi
+
 			if [[ -z "$JOBLIST" ]]; then
                 JOBLIST="${1%%.*}"
             else
@@ -177,26 +204,17 @@ while [[ $# -gt 0 ]]; do
             fi
 			;;
         [a-zA-Z]*)
+            if [[ $1 == *@* ]]; then
+                CUSTOMSERVER=${1#*@} find_server
+            fi
+
 			if [[ -z "$JOBLIST" ]]; then
-                DESTLIST="${1}"
+                DESTLIST="${1%%@*}"
             else
-                DESTLIST="$DESTLIST|${1}"
+                DESTLIST="$DESTLIST|${1%%@*}"
             fi
 			;;
-        @*)
-            CUSTOM_SERVER=${1:1}
-
-            if [[ ! -f $MYPATH/${CUSTOM_SERVER}.cfg ]]; then
-                >&2 echo "Error: $CUSTOM_SERVER is not a valid server"
-                exit 1
-            fi
-            ;;
         *)
-            if [[ -n $CUSTOM_SERVER ]] || [[ "$@" == *@* ]]; then
-                >&2 echo "Error: option $1 is not available across servers"
-                exit 1
-            fi
-
             load_config
 
             if [[ ! -f $QSTATBIN ]]; then
@@ -214,10 +232,6 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Load chosen server config
-if [[ -n $CUSTOM_SERVER ]]; then
-    QSCACHE_SERVER=$CUSTOM_SERVER
-fi
-
 load_config
 
 if [[ $QSCACHE_BYPASS == true ]]; then
